import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@styles/styles.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 16x16   → browser tab
// 32x32   → bookmarks
// 48x48   → Windows
// 180x180 → iOS (Apple)
// 192x192 → Android
// 512x512 → PWA / install

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
